#!/bin/bash
# This script runs SPLASH on the example data generated by generate_example_data.sh
# It assumes that the example data is in the example_data directory and that the sample sheet is named sample_sheet.tsv
# It also assumes that SPLASH is installed and available in the splash-2.11.6 directory
# Usage: ./run_splash.sh
# Check if SPLASH is installed
if [ ! -d "splash-2.11.6" ]; then
    echo "SPLASH is not downloaded. Please download SPLASH and try again."
    exit 1
fi

# Check if example data directory exists
if [ ! -d "example_data" ]; then
    echo "Example data directory does not exist. Please run generate_example_data.sh first."
    exit 1
fi

# check if sample sheet exists
if [ ! -f "example_data/sample_sheet.txt" ]; then
    echo "Sample sheet does not exist. Please run generate_example_data.sh first."
    exit 1
fi

mkdir -p H5N1-splash-results

cp example_data/sample_sheet.txt H5N1-splash-results

cd H5N1-splash-results

# Run SPLASH with the provided parameters
../splash-2.11.6/splash \
    --outname_prefix result \
    --anchor_len 27 \
    --gap_len 0 \
    --target_len 27 \
    --poly_ACGT_len 8 \
    --max_pval_opt_for_Cjs 0.05 \
    --with_effect_size_cts \
    --with_pval_asymp_opt \
    --n_threads_stage_1 4 \
    --n_threads_stage_2 4 \
    --n_bins 64 \
    --n_most_freq_targets 10 \
    --dump_sample_anchor_target_count_binary \
    --satc_merge_dump_format satc \
    --without_compactors \
    sample_sheet.txt
