executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/`date +"%d-%m-%y"`/{rule};
  sbatch
    --parsable
    --time={resources.time}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}
    --output=logs/`date +"%d-%m-%y"`/{rule}/{rule}-%j.out
    {resources.slurm_extra}
default-resources:
  - time="2:00:00"
  - partition="horence,owners,normal"
  - mem_mb=4000
  - slurm_extra=""
resources:
  - msa=10 # sets msa=10 to limit rules that use the R msa package
jobs: 2000
local-cores: 1
max-jobs-per-second: 500
max-status-checks-per-second: 15
restart-times: 2
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
benchmark-extended: True
cluster-generic-cancel-cmd: scancel
scheduler: greedy
set-threads: # set specific threads for each rule
    choose_anchors: 4
    cluster_anchors: 4
    reorder_clusters: 32
    prepare_sequences: 64
    decompose_kmers: 4
    match_kmers_to_clusters: 1
    embed_kmers_hyena: 8
    prepare_data_for_prediction_top_variance: 32
    prepare_data_for_prediction_pca: 48
    prepare_data_for_umap_top_variance: 32
    run_adelie: 64
    prepare_data_for_prediction_ohe: 4
    run_adelie_ohe: 32
    process_genome_to_sample_sequences: 16
    decompose_kmers_genomes: 4
    embed_kmers_hyena_genomes: 8
    prepare_data_for_prediction_genomes: 32
    run_adelie_genomes: 64
    annotate_clusters: 4
    merge_annotations: 1
    run_blast_nonzero_features: 32
    run_blastp_nonzero_features: 32
    merge_blast_results: 1
    merge_blastp_results: 1
    merge_annotations_OHE: 1
    run_blast_nonzero_features_OHE: 32
    run_blastp_nonzero_features_OHE: 32
    merge_blast_results_OHE: 1
    merge_blastp_results_OHE: 1
    merge_annotations_genomes: 1
    plot_blast_features: 1
    plot_blast_heatmaps: 1
    plot_blast_features_OHE: 1
    plot_blast_heatmaps_OHE: 1
    prepare_data_for_umap_top_variance: 32
    plot_embeddings_umap: 16
set-resources: # set specific resources for each rule
    choose_anchors:
        mem_mb: 128000 + ((attempt - 1) * 64000)
        time: "4:00:00"
    cluster_anchors:
    # increase time for larger datasets or more complex clustering
        mem_mb: 256000 + ((attempt - 1) * 256000)
        time: "10:00:00" 
    reorder_clusters:
        mem_mb: 64000 + ((attempt - 1) * 64000)
        time: "5:00:00"
    prepare_sequences:
        mem_mb: 256000 + ((attempt - 1) * 256000)
        time: "12:00:00"
    decompose_kmers:
        mem_mb: 32000 + ((attempt - 1) * 32000)
        time: "3:00:00"
    match_kmers_to_clusters:
        mem_mb: 16000 + ((attempt - 1) * 16000)
    embed_kmers_hyena:
        mem_mb: 32000
        time: "6:00:00"
        partition: "horence"
        slurm_extra: "-G 1 -C 'GPU_SKU:H100_SXM5'"
    prepare_data_for_prediction_top_variance:
        mem_mb: 256000 + ((attempt - 1) * 256000)
        time: "6:00:00"
    prepare_data_for_prediction_pca:
        mem_mb: 256000 + ((attempt - 1) * 256000)
        time: "6:00:00"
    prepare_data_for_umap_top_variance:
        mem_mb: 256000 + ((attempt - 1) * 256000)
        time: "6:00:00"
    run_adelie:
        mem_mb: 512000 + ((attempt - 1) * 256000)
        time: "24:00:00"
    prepare_data_for_prediction_ohe:
        mem_mb: 96000 + ((attempt - 1) * 64000)
        time: "3:00:00"
    run_adelie_ohe:
        mem_mb: 512000 + ((attempt - 1) * 256000)
        time: "18:00:00"
    process_genome_to_sample_sequences:
        mem_mb: 128000 + ((attempt - 1) * 64000)
    decompose_kmers_genomes:
        mem_mb: 16000 + ((attempt - 1) * 16000)
        time: "3:00:00"
    embed_kmers_hyena_genomes:
        mem_mb: 32000
        time: "3:00:00"
        partition: "horence,gpu,owners"
        slurm_extra: "-G 1 -C 'GPU_GEN:HPR|GPU_GEN:AMP|GPU_GEN:TUR'"
    prepare_data_for_prediction_genomes:
        mem_mb: 256000 + ((attempt - 1) * 256000)
    run_adelie_genomes:
        mem_mb: 512000 + ((attempt - 1) * 128000)
        time: "36:00:00"
    annotate_clusters:
        mem_mb: 64000 + ((attempt - 1) * 32000)
    merge_annotations:
        mem_mb: 64000 + ((attempt - 1) * 32000)
    run_blast_nonzero_features:
        mem_mb: 128000 + ((attempt - 1) * 128000)
        time: "9:00:00"
    run_blastp_nonzero_features:
        mem_mb: 256000 + ((attempt - 1) * 128000)
        time: "12:00:00"
    merge_blast_results:
        mem_mb: 8000 + ((attempt - 1) * 16000)
    merge_blastp_results:
        mem_mb: 8000 + ((attempt - 1) * 16000)
    merge_annotations_OHE:
        mem_mb: 32000
    run_blast_nonzero_features_OHE:
        mem_mb: 128000 + ((attempt - 1) * 128000)
        time: "9:00:00"
    run_blastp_nonzero_features_OHE:
        mem_mb: 256000 + ((attempt - 1) * 128000)
        time: "9:00:00"
    merge_blast_results_OHE:
        mem_mb: 8000 + ((attempt - 1) * 16000)
    merge_blastp_results_OHE:
        mem_mb: 8000 + ((attempt - 1) * 16000)
    merge_annotations_genomes:
        mem_mb: 32000
    plot_blast_features:
        mem_mb: 256000 + ((attempt - 1) * 128000)
        msa: 1
        time: "4:00:00"
    plot_blast_heatmaps:
        mem_mb: 128000 + ((attempt - 1) * 128000)
        time: "4:00:00"
    plot_blast_features_OHE:
        mem_mb: 128000 + ((attempt - 1) * 128000)
        msa: 1
    plot_blast_heatmaps_OHE:
        mem_mb: 128000 + ((attempt - 1) * 128000)
    prepare_data_for_umap_top_variance:
        mem_mb: 256000 + ((attempt - 1) * 256000)
        time: "6:00:00"
    plot_embeddings_umap:
        mem_mb: 128000 + ((attempt - 1) * 128000)
        time: "2:00:00"