executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/`date +"%d-%m-%y"`/{rule};
  sbatch
    --parsable
    --time={resources.time}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/`date +"%d-%m-%y"`/{rule}/{rule}-{wildcards}-%j.out
    {resources.slurm_extra}
default-resources:
  - time="2:00:00"
  - partition="horence,owners,normal"
  - mem_mb=4000
  - slurm_extra=""
  - msa=1
jobs: 2000
local-cores: 1
max-jobs-per-second: 500
max-status-checks-per-second: 15
restart-times: 2
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
benchmark-extended: True
cluster-generic-cancel-cmd: scancel
scheduler: greedy